load('ext://namespace', 'namespace_create')

helpers = load_dynamic("../tilt/extensions/Tiltfile")
helmfile_with_local_chart = helpers['helmfile_with_local_chart']

allow_k8s_contexts(['kind-vydon-dev', 'orbstack'])

secret_settings(disable_scrub=True)

namespace_create('vydon', allow_duplicates=True)

base_dir = os.path.dirname(__file__)
repo_root = os.path.dirname(base_dir)
helmfileDir = base_dir + '/apps/web/dev/helm/app'

k8s_yaml(helmfile_with_local_chart('vydon-app', base_dir + '/apps/web/charts/app', helmfileDir=helmfileDir))
k8s_resource(
  'vydon-app',
  labels=['frontend'],
  port_forwards='3000:3000',
)

docker_build(
  ref='vydon-app',
  context=base_dir,
  dockerfile=repo_root + '/docker/Dockerfile.frontend',
)
