load('ext://namespace', 'namespace_create')

helpers = load_dynamic("../tilt/extensions/Tiltfile")
helmfile_with_local_chart = helpers['helmfile_with_local_chart']
helmfile = helpers['helmfile']

allow_k8s_contexts(['kind-vydon-dev', 'orbstack'])

base_dir = os.path.dirname(__file__)
repo_root = os.path.dirname(base_dir)

secret_settings(disable_scrub=True)

namespace_create('vydon', allow_duplicates=True)

k8s_yaml(kustomize('./dev/yaml'))
k8s_resource('vydon-postgresql', labels=['db'], port_forwards=5432)

k8s_yaml(helmfile_with_local_chart('vydon-api', base_dir + '/charts/api', helmfileDir=base_dir + '/dev/helm/api'))
k8s_resource(
  'vydon-api',
  resource_deps=['vydon-postgresql'],
  labels=['backend'],
  port_forwards="8080:8080",
)

docker_build(
  ref='vydon-api',
  context=repo_root,
  dockerfile=repo_root + '/docker/Dockerfile.backend',
)
