image:
  repository: vydon-api

serviceAccount:
  create: true

db:
  host: vydon-postgresql
  name: vydon
  port: 5432
  username: postgres
  password: foofar
  disableSsl: true

migrations:
  db:
    host: vydon-postgresql
    name: vydon
    port: 5432
    username: postgres
    password: foofar
    disableSsl: true
    schemaDir: /migrations

terminationGracePeriodSeconds: 300
shutdownTimeoutSeconds: 5

istio:
  enabled: false

datadog:
  enabled: false

vydonEnv: dev

servicePort: 80
containerPort: 8080

auth:
  baseUrl: https://auth.vydon-io.dev/
  audience: https://api.vydon.io

temporal:
  url: temporal.temporal.svc.cluster.local:7233
  namespace: default
  taskQueue: "sync-job"

ingress:
  enabled: false
