# Build the manager binary
FROM golang:1.25-bookworm@sha256:e3a54b77385b4f8a31c1db4d12429ffb3718ea76865731a787c497755d409547 AS builder

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive \
  apt-get install --no-install-recommends -y \
  build-essential

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download

WORKDIR /workspace
COPY backend/internal/ backend/internal/
COPY backend/pkg/ backend/pkg/
COPY backend/sql backend/sql/
COPY backend/gen/ backend/gen/
COPY internal/ internal/

WORKDIR /workspace/worker

# Copy the go source
COPY worker/cmd/ cmd/
COPY worker/internal/ internal/
COPY worker/pkg/ pkg/

# Build
RUN go build -ldflags="-s -w" -o bin/worker cmd/worker/*.go

# Use debian:bullseye-slim as the base image to include necessary C libraries
FROM debian:bookworm-slim@sha256:67b30a61dc87758f0caf819646104f29ecbda97d920aaf5edc834128ac8493d3
WORKDIR /

# Install CA certificates for HTTPS connections
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive \
  apt-get install --no-install-recommends -y ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /workspace/worker/bin/worker .

# Create a non-root user
RUN useradd -u 65532 -r nonroot
USER nonroot

ENTRYPOINT ["/worker"]

CMD ["serve"]
