load('ext://namespace', 'namespace_create')

helpers = load_dynamic("../tilt/extensions/Tiltfile")
helmfile_with_local_chart = helpers['helmfile_with_local_chart']

allow_k8s_contexts(['kind-vydon-dev', 'orbstack'])

base_dir = os.path.dirname(__file__)
repo_root = os.path.dirname(base_dir)

secret_settings(disable_scrub=True)

namespace_create('vydon', allow_duplicates=True)

k8s_yaml(helmfile_with_local_chart('vydon-worker', base_dir + '/charts/worker', helmfileDir=base_dir + '/dev/helm'))
k8s_resource(
  'vydon-worker',
  resource_deps=[],
  labels=['backend'],
)

docker_build(
  ref='vydon-worker',
  context=repo_root,
  dockerfile=repo_root + '/docker/Dockerfile.worker',
)
