name: Dev Container Build and Push Image

on:
  push:
    tags:
      - "devcontainer/v*.*.*"

permissions:
  contents: read

jobs:
  devcontainer-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Compute tag for devcontainer image
        id: meta
        run: |
          tag="${GITHUB_REF#refs/tags/devcontainer/v}"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Set up Depot CLI
        uses: depot/setup-action@15c09a5f77a0840ad4bce955686522a257853461 # v1
        with:
          oidc: true

      - name: Setup Docker to use Depot
        run: depot configure-docker

      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and release devcontainer Multi-Platform
        run: |
          npm install -g @devcontainers/cli
          devcontainer build \
            --workspace-folder .github \
            --image-name ghcr.io/${{ github.repository }}/devcontainer:${{ steps.meta.outputs.tag }} \
            --image-name ghcr.io/${{ github.repository }}/devcontainer:latest \
            --platform linux/amd64,linux/arm64 \
            --push
        env:
          # see: https://github.com/devcontainers/ci/issues/191#issuecomment-1603857155
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
