apiVersion: v1
kind: Service
metadata:
  name: {{ template "vydon-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "vydon-app.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ template "vydon-app.fullname" . }}
